model: SeqRecModel
#model_infer: seq_rec_infer
seed: 1
reproducibility: True

model:
  embedding_size: 64
  hidden_size: 64
  num_layers: 2
  dropout_prob: 0.2

runner:
  batch_size: 128
  epochs: 10
  early_stop: 3
  eval_step: 1
  use_gpu: False

dataset:
  name: u1
  data_path: /home/eduardo/masters/MovieLens-100k/data/
  fields_in_same_space: false
  load_col: [user_id, item_id_list,item_id ]
  benchmark_filename: [base, train, valid] 
  separator: '   '
  seq_len: 5
  item_num: 100

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
ITEM_LIST_LENGTH_FIELD: item_id_list
MAX_ITEM_LIST_LENGTH: 5

valid_metric: MRR@10
eval_args: {split: {RS: [1,0,0]}, group_by: user, order: TO, mode: full}
topk: 10